export const dynamic = 'force-dynamic';

import type { Metadata } from "next";
import "@/app/globals.css";
import FlashMessage from "@/components/ui/FlashMessage";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <FlashMessage />
      {children}
    </>
  );
}
