import React from 'react'
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css'
import { Metadata } from 'next';
import ApolloProvider from './ApolloProvider';
import FlashMessage from '@/components/ui/FlashMessage';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ApolloProvider>
          <FlashMessage />
          {children}
        </ApolloProvider>
      </body>
    </html>
  )
}
