import type { Metadata } from "next";
import styles from "./layout.module.css";
import "@/app/globals.css";
import PublicHeader from "@/components/layouts/PublicHeader/PublicHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <main className={styles.container}>
      <PublicHeader />
      {children}
      {modal}
    </main>
  );
}
