import type { Metadata } from "next";
import styles from "./layout.module.css";
import "@/app/globals.css";
import PrivateHeader from "@/components/layouts/PrivateHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className={styles.container}>
      <PrivateHeader />
      {children}
    </main>
  );
}
